services:
  storefront:
    container_name: nextJs-Ventrue-Starter-Template-Container
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    #AS This compose is made to be used with a proxy, ports are not being exposed
    # if you need any port mapping from container<-> host, uncomment
    # ports:
    #   - 8000:8000

    depends_on:
      - database
    env_file:
      - ./.env
    networks:
      #TO BE USED WITH NGINX PROXY MANAGER, comment if your are exposing it directly
      frontend:
        ipv4_address: 192.168.1.24

  database:
    image: postgres:latest
    container_name: nextJs-Ventrue-Postgres
    restart: unless-stopped
    volumes:
      - ./backups:/docker-entrypoint-initdb.d
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      #Persistent database under prisma directory
      - ./prisma/database/:/var/lib/postgresql/data
      
    env_file:
      - ./.env
      
    networks:
      backend:

networks:
  #TO BE USED WITH NGINX PROXY MANAGER, comment if your are exposing it directly
  frontend:
    name: proxy
    external: true

  #Internal network of the stack
  backend:
    name:  nextJs-Ventrue-network